// <auto-generated />
using Challenge_Flextech.Persistence.MsSql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Challenge_Flextech.Migrations
{
    [DbContext(typeof(MsSqlContext))]
    partial class MsSqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Challenge_Flextech.Persistence.Model.MovimientosBcraModel", b =>
                {
                    b.Property<string>("cuentaAcreedora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cuentaDeudora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("entidadAcreedora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("entidadDeudora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaProcesado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("importe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("instruccionDePago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numeroInterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("operatoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("transaccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("movimientosBcra");
                });
#pragma warning restore 612, 618
        }
    }
}
